name: allennlp_elmo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.6.13
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - aiohttp==3.7.4.post0
    - alabaster==0.7.12
    - astroid==2.5.6
    - async-timeout==3.0.1
    - attrs==21.2.0
    - babel==2.9.1
    - bleach==3.3.0
    - blis==0.2.4
    - boto3==1.17.74
    - botocore==1.20.74
    - cached-property==1.5.2
    - cffi==1.14.5
    - chardet==4.0.0
    - click==8.0.0
    - codecov==2.1.11
    - colorama==0.4.4
    - conllu==1.3.1
    - coverage==5.5
    - cryptography==3.4.7
    - cycler==0.10.0
    - cymem==2.0.5
    - dataclasses==0.8
    - docutils==0.16
    - editdistance==0.5.3
    - en-core-web-sm==2.1.0
    - flaky==3.7.0
    - flask==2.0.0
    - flask-cors==3.0.10
    - ftfy==6.0.1
    - gevent==21.1.2
    - greenlet==1.1.0
    - h5py==3.1.0
    - idna==2.10
    - idna-ssl==1.1.0
    - imagesize==1.2.0
    - importlib-metadata==4.0.1
    - iniconfig==1.1.1
    - isort==5.8.0
    - itsdangerous==2.0.0
    - jeepney==0.6.0
    - jinja2==3.0.0
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsonnet==0.17.0
    - jsonpickle==2.0.0
    - keyring==23.0.1
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.6.0
    - livereload==2.6.3
    - markupsafe==2.0.0
    - matplotlib==3.3.4
    - mccabe==0.6.1
    - multidict==5.1.0
    - murmurhash==1.0.5
    - mypy==0.812
    - mypy-extensions==0.4.3
    - nltk==3.6.2
    - numpy==1.19.5
    - numpydoc==1.1.0
    - overrides==3.1.0
    - packaging==20.9
    - parsimonious==0.8.1
    - pillow==8.2.0
    - pkginfo==1.7.0
    - plac==0.9.6
    - pluggy==0.13.1
    - preshed==2.0.1
    - protobuf==3.17.0
    - py==1.10.0
    - pycparser==2.20
    - pygments==2.9.0
    - pylint==2.8.2
    - pypandoc==1.5
    - pyparsing==2.4.7
    - pytest==6.2.4
    - pytest-cov==2.12.0
    - python-dateutil==2.8.1
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pytz==2021.1
    - readme-renderer==29.0
    - regex==2021.4.4
    - requests==2.25.1
    - requests-toolbelt==0.9.1
    - responses==0.13.3
    - rfc3986==1.5.0
    - s3transfer==0.4.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - secretstorage==3.3.1
    - sentencepiece==0.1.95
    - six==1.16.0
    - snowballstemmer==2.1.0
    - spacy==2.1.9
    - sphinx==3.5.4
    - sphinx-autobuild==2021.3.14
    - sphinx-rtd-theme==0.5.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlparse==0.4.1
    - srsly==1.0.5
    - tensorboardx==2.2
    - thinc==7.0.8
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - torch==1.8.1
    - tornado==6.1
    - tqdm==4.60.0
    - twine==3.4.1
    - typed-ast==1.4.3
    - typing-extensions==3.10.0.0
    - typing-utils==0.0.3
    - unidecode==1.2.0
    - urllib3==1.26.4
    - wasabi==0.8.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - word2number==1.1
    - wrapt==1.12.1
    - yarl==1.6.3
    - zipp==3.4.1
    - zope-event==4.5.0
    - zope-interface==5.4.0
